// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhurCgyO2zVJTIzhAb0Pkc1DjeE0BkIDI',
    appId: '1:391390004819:web:26b474f61df3f0e978a8a6',
    messagingSenderId: '391390004819',
    projectId: 'lokal-app-38e9f',
    authDomain: 'lokal-app-38e9f.firebaseapp.com',
    databaseURL: 'https://lokal-app-38e9f-default-rtdb.firebaseio.com',
    storageBucket: 'lokal-app-38e9f.appspot.com',
    measurementId: 'G-SCNM0YG4SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjBJQ55gpN-6GZPijpIsO6w0yp_O3GYzE',
    appId: '1:391390004819:android:272bdcf1061fca8278a8a6',
    messagingSenderId: '391390004819',
    projectId: 'lokal-app-38e9f',
    databaseURL: 'https://lokal-app-38e9f-default-rtdb.firebaseio.com',
    storageBucket: 'lokal-app-38e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNIat0qrNzDz2PbqXoC3-lAztbmj5G10',
    appId: '1:391390004819:ios:7de016a7d8aac87b78a8a6',
    messagingSenderId: '391390004819',
    projectId: 'lokal-app-38e9f',
    databaseURL: 'https://lokal-app-38e9f-default-rtdb.firebaseio.com',
    storageBucket: 'lokal-app-38e9f.appspot.com',
    iosClientId: '391390004819-vp77gircg0hn9kcjfs5hfgmsio6r2jmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNIat0qrNzDz2PbqXoC3-lAztbmj5G10',
    appId: '1:391390004819:ios:7de016a7d8aac87b78a8a6',
    messagingSenderId: '391390004819',
    projectId: 'lokal-app-38e9f',
    databaseURL: 'https://lokal-app-38e9f-default-rtdb.firebaseio.com',
    storageBucket: 'lokal-app-38e9f.appspot.com',
    iosClientId: '391390004819-vp77gircg0hn9kcjfs5hfgmsio6r2jmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
