-verbose
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.lokal.app.MainActivity
-keep class com.lokal.app.MyApplication
-keep class com.lokal.app.** { *; }
-keep class com.google.firebase.** { *; }